using UnityEngine;
namespace BS
{
    public class BSComponentFromType
    {
        public static BSComponentBase CreateComponent(GameObject gameObject, ComponentType componentType)
        {
            switch (componentType)
            {
                case ComponentType.AOBaking:
                    return gameObject.AddComponent<BSAOBaking>();
                case ComponentType.Apple:
                    return gameObject.AddComponent<BSApple>();
                case ComponentType.AssetBundle:
                    return gameObject.AddComponent<BSAssetBundle>();
                case ComponentType.AttachedObject:
                    return gameObject.AddComponent<BSAttachedObject>();
                case ComponentType.AudioSource:
                    return gameObject.AddComponent<BSAudioSource>();
                case ComponentType.Billboard:
                    return gameObject.AddComponent<BSBillboard>();
                case ComponentType.Box:
                    return gameObject.AddComponent<BSBox>();
                case ComponentType.BoxCollider:
                    return gameObject.AddComponent<BSBoxCollider>();
                case ComponentType.Browser:
                    return gameObject.AddComponent<BSBrowser>();
                case ComponentType.CapsuleCollider:
                    return gameObject.AddComponent<BSCapsuleCollider>();
                case ComponentType.Catenoid:
                    return gameObject.AddComponent<BSCatenoid>();
                case ComponentType.CharacterJoint:
                    return gameObject.AddComponent<BSCharacterJoint>();
                case ComponentType.Circle:
                    return gameObject.AddComponent<BSCircle>();
                case ComponentType.ColliderEvents:
                    return gameObject.AddComponent<BSColliderEvents>();
                case ComponentType.Cone:
                    return gameObject.AddComponent<BSCone>();
                case ComponentType.ConfigurableJoint:
                    return gameObject.AddComponent<BSConfigurableJoint>();
                case ComponentType.Cylinder:
                    return gameObject.AddComponent<BSCylinder>();
                case ComponentType.Fermet:
                    return gameObject.AddComponent<BSFermet>();
                case ComponentType.FixedJoint:
                    return gameObject.AddComponent<BSFixedJoint>();
                case ComponentType.Geometry:
                    return gameObject.AddComponent<BSGeometry>();
                case ComponentType.GLTF:
                    return gameObject.AddComponent<BSGLTF>();
                case ComponentType.Grababble:
                    return gameObject.AddComponent<BSGrababble>();
                case ComponentType.GrabHandle:
                    return gameObject.AddComponent<BSGrabHandle>();
                case ComponentType.HeldEvents:
                    return gameObject.AddComponent<BSHeldEvents>();
                case ComponentType.Helicoid:
                    return gameObject.AddComponent<BSHelicoid>();
                case ComponentType.HingeJoint:
                    return gameObject.AddComponent<BSHingeJoint>();
                case ComponentType.Horn:
                    return gameObject.AddComponent<BSHorn>();
                case ComponentType.InvertedMesh:
                    return gameObject.AddComponent<BSInvertedMesh>();
                case ComponentType.KitItem:
                    return gameObject.AddComponent<BSKitItem>();
                case ComponentType.Klein:
                    return gameObject.AddComponent<BSKlein>();
                case ComponentType.Light:
                    return gameObject.AddComponent<BSLight>();
                case ComponentType.Material:
                    return gameObject.AddComponent<BSMaterial>();
                case ComponentType.MeshCollider:
                    return gameObject.AddComponent<BSMeshCollider>();
                case ComponentType.Mirror:
                    return gameObject.AddComponent<BSMirror>();
                case ComponentType.Mobius:
                    return gameObject.AddComponent<BSMobius>();
                case ComponentType.Mobius3d:
                    return gameObject.AddComponent<BSMobius3d>();
                case ComponentType.MonoBehaviour:
                    return gameObject.AddComponent<BSMonoBehaviour>();
                case ComponentType.Natica:
                    return gameObject.AddComponent<BSNatica>();
                case ComponentType.PhysicMaterial:
                    return gameObject.AddComponent<BSPhysicMaterial>();
                case ComponentType.PhysicsMaterial:
                    return gameObject.AddComponent<BSPhysicsMaterial>();
                case ComponentType.Pillow:
                    return gameObject.AddComponent<BSPillow>();
                case ComponentType.Plane:
                    return gameObject.AddComponent<BSPlane>();
                case ComponentType.Portal:
                    return gameObject.AddComponent<BSPortal>();
                case ComponentType.QuestHome:
                    return gameObject.AddComponent<BSQuestHome>();
                case ComponentType.Rigidbody:
                    return gameObject.AddComponent<BSRigidbody>();
                case ComponentType.Ring:
                    return gameObject.AddComponent<BSRing>();
                case ComponentType.Scherk:
                    return gameObject.AddComponent<BSScherk>();
                case ComponentType.SkinnedMeshRenderer:
                    return gameObject.AddComponent<BSSkinnedMeshRenderer>();
                case ComponentType.Snail:
                    return gameObject.AddComponent<BSSnail>();
                case ComponentType.Sphere:
                    return gameObject.AddComponent<BSSphere>();
                case ComponentType.SphereCollider:
                    return gameObject.AddComponent<BSSphereCollider>();
                case ComponentType.Spiral:
                    return gameObject.AddComponent<BSSpiral>();
                case ComponentType.Spring:
                    return gameObject.AddComponent<BSSpring>();
                case ComponentType.SpringJoint:
                    return gameObject.AddComponent<BSSpringJoint>();
                case ComponentType.StreetView:
                    return gameObject.AddComponent<BSStreetView>();
                case ComponentType.SyncedObject:
                    return gameObject.AddComponent<BSSyncedObject>();
                case ComponentType.Text:
                    return gameObject.AddComponent<BSText>();
                case ComponentType.Torus:
                    return gameObject.AddComponent<BSTorus>();
                case ComponentType.TorusKnot:
                    return gameObject.AddComponent<BSTorusKnot>();
                case ComponentType.UIPanel:
                    return gameObject.AddComponent<BSUIPanel>();
                case ComponentType.VideoPlayer:
                    return gameObject.AddComponent<BSVideoPlayer>();
                case ComponentType.WorldObject:
                    return gameObject.AddComponent<BSWorldObject>();
                default:
                    return null;
            }
        }
    }
}
