using UnityEngine;
namespace Banter.SDK
{
    public class BanterComponentFromType
    {
        public static BanterComponentBase CreateComponent(GameObject gameObject, ComponentType componentType)
        {
            switch (componentType)
            {
                case ComponentType.BanterApple:
                    return gameObject.AddComponent<BanterApple>();
                case ComponentType.BanterAssetBundle:
                    return gameObject.AddComponent<BanterAssetBundle>();
                case ComponentType.BanterAttachedObject:
                    return gameObject.AddComponent<BanterAttachedObject>();
                case ComponentType.BanterAudioSource:
                    return gameObject.AddComponent<BanterAudioSource>();
                case ComponentType.BanterAvatarPedestal:
                    return gameObject.AddComponent<BanterAvatarPedestal>();
                case ComponentType.BanterBillboard:
                    return gameObject.AddComponent<BanterBillboard>();
                case ComponentType.BanterBox:
                    return gameObject.AddComponent<BanterBox>();
                case ComponentType.BoxCollider:
                    return gameObject.AddComponent<BanterBoxCollider>();
                case ComponentType.BanterBrowser:
                    return gameObject.AddComponent<BanterBrowser>();
                case ComponentType.CapsuleCollider:
                    return gameObject.AddComponent<BanterCapsuleCollider>();
                case ComponentType.BanterCatenoid:
                    return gameObject.AddComponent<BanterCatenoid>();
                case ComponentType.CharacterJoint:
                    return gameObject.AddComponent<BanterCharacterJoint>();
                case ComponentType.BanterCircle:
                    return gameObject.AddComponent<BanterCircle>();
                case ComponentType.BanterColliderEvents:
                    return gameObject.AddComponent<BanterColliderEvents>();
                case ComponentType.BanterCone:
                    return gameObject.AddComponent<BanterCone>();
                case ComponentType.ConfigurableJoint:
                    return gameObject.AddComponent<BanterConfigurableJoint>();
                case ComponentType.BanterCylinder:
                    return gameObject.AddComponent<BanterCylinder>();
                case ComponentType.BanterFermet:
                    return gameObject.AddComponent<BanterFermet>();
                case ComponentType.FixedJoint:
                    return gameObject.AddComponent<BanterFixedJoint>();
                case ComponentType.BanterGeometry:
                    return gameObject.AddComponent<BanterGeometry>();
                case ComponentType.BanterGLTF:
                    return gameObject.AddComponent<BanterGLTF>();
                case ComponentType.BanterGrababble:
                    return gameObject.AddComponent<BanterGrababble>();
                case ComponentType.BanterGrabHandle:
                    return gameObject.AddComponent<BanterGrabHandle>();
                case ComponentType.BanterHeldEvents:
                    return gameObject.AddComponent<BanterHeldEvents>();
                case ComponentType.BanterHelicoid:
                    return gameObject.AddComponent<BanterHelicoid>();
                case ComponentType.HingeJoint:
                    return gameObject.AddComponent<BanterHingeJoint>();
                case ComponentType.BanterHorn:
                    return gameObject.AddComponent<BanterHorn>();
                case ComponentType.BanterInvertedMesh:
                    return gameObject.AddComponent<BanterInvertedMesh>();
                case ComponentType.BanterKitItem:
                    return gameObject.AddComponent<BanterKitItem>();
                case ComponentType.BanterKlein:
                    return gameObject.AddComponent<BanterKlein>();
                case ComponentType.Light:
                    return gameObject.AddComponent<BanterLight>();
                case ComponentType.BanterMaterial:
                    return gameObject.AddComponent<BanterMaterial>();
                case ComponentType.MeshCollider:
                    return gameObject.AddComponent<BanterMeshCollider>();
                case ComponentType.BanterMirror:
                    return gameObject.AddComponent<BanterMirror>();
                case ComponentType.BanterMobius:
                    return gameObject.AddComponent<BanterMobius>();
                case ComponentType.BanterMobius3d:
                    return gameObject.AddComponent<BanterMobius3d>();
                case ComponentType.BanterMonoBehaviour:
                    return gameObject.AddComponent<BanterMonoBehaviour>();
                case ComponentType.BanterNatica:
                    return gameObject.AddComponent<BanterNatica>();
                case ComponentType.BanterPhysicMaterial:
                    return gameObject.AddComponent<BanterPhysicMaterial>();
                case ComponentType.BanterPhysicsMaterial:
                    return gameObject.AddComponent<BanterPhysicsMaterial>();
                case ComponentType.BanterPillow:
                    return gameObject.AddComponent<BanterPillow>();
                case ComponentType.BanterPlane:
                    return gameObject.AddComponent<BanterPlane>();
                case ComponentType.BanterPortal:
                    return gameObject.AddComponent<BanterPortal>();
                case ComponentType.BanterQuestHome:
                    return gameObject.AddComponent<BanterQuestHome>();
                case ComponentType.BanterRigidbody:
                    return gameObject.AddComponent<BanterRigidbody>();
                case ComponentType.BanterRing:
                    return gameObject.AddComponent<BanterRing>();
                case ComponentType.BanterScherk:
                    return gameObject.AddComponent<BanterScherk>();
                case ComponentType.SkinnedMeshRenderer:
                    return gameObject.AddComponent<BanterSkinnedMeshRenderer>();
                case ComponentType.BanterSnail:
                    return gameObject.AddComponent<BanterSnail>();
                case ComponentType.BanterSphere:
                    return gameObject.AddComponent<BanterSphere>();
                case ComponentType.SphereCollider:
                    return gameObject.AddComponent<BanterSphereCollider>();
                case ComponentType.BanterSpiral:
                    return gameObject.AddComponent<BanterSpiral>();
                case ComponentType.BanterSpring:
                    return gameObject.AddComponent<BanterSpring>();
                case ComponentType.SpringJoint:
                    return gameObject.AddComponent<BanterSpringJoint>();
                case ComponentType.BanterStreetView:
                    return gameObject.AddComponent<BanterStreetView>();
                case ComponentType.BanterSyncedObject:
                    return gameObject.AddComponent<BanterSyncedObject>();
                case ComponentType.BanterText:
                    return gameObject.AddComponent<BanterText>();
                case ComponentType.BanterTorus:
                    return gameObject.AddComponent<BanterTorus>();
                case ComponentType.BanterTorusKnot:
                    return gameObject.AddComponent<BanterTorusKnot>();
                case ComponentType.BanterUIPanel:
                    return gameObject.AddComponent<BanterUIPanel>();
                case ComponentType.BanterVideoPlayer:
                    return gameObject.AddComponent<BanterVideoPlayer>();
                case ComponentType.BanterWorldObject:
                    return gameObject.AddComponent<BanterWorldObject>();
                default:
                    return null;
            }
        }
    }
}
