namespace Banter.SDK
{
    public enum ComponentType
    {
        Transform,
        AOBaking,
        Apple,
        AssetBundle,
        AttachedObject,
        AudioSource,
        AvatarPedestal,
        Billboard,
        Box,
        BoxCollider,
        Browser,
        CapsuleCollider,
        Catenoid,
        CharacterJoint,
        Circle,
        ColliderEvents,
        Cone,
        ConfigurableJoint,
        Cylinder,
        Fermet,
        FixedJoint,
        Geometry,
        GLTF,
        Grababble,
        GrabHandle,
        HeldEvents,
        Helicoid,
        HingeJoint,
        Horn,
        InvertedMesh,
        KitItem,
        Klein,
        Light,
        Material,
        MeshCollider,
        Mirror,
        Mobius,
        Mobius3d,
        MonoBehaviour,
        Natica,
        PhysicMaterial,
        PhysicsMaterial,
        Pillow,
        Plane,
        Portal,
        QuestHome,
        Rigidbody,
        Ring,
        Scherk,
        SkinnedMeshRenderer,
        Snail,
        Sphere,
        SphereCollider,
        Spiral,
        Spring,
        SpringJoint,
        StreetView,
        SyncedObject,
        Text,
        Torus,
        TorusKnot,
        UIPanel,
        VideoPlayer,
        WorldObject,

        // Deprecated aliases for the pre-rename names. Same values, so they stay
        // wire-compatible; kept so existing content and scripts keep resolving.
        BanterAOBaking = AOBaking,
        BanterApple = Apple,
        BanterAssetBundle = AssetBundle,
        BanterAttachedObject = AttachedObject,
        BanterAudioSource = AudioSource,
        BanterAvatarPedestal = AvatarPedestal,
        BanterBillboard = Billboard,
        BanterBox = Box,
        BanterBrowser = Browser,
        BanterCatenoid = Catenoid,
        BanterCircle = Circle,
        BanterColliderEvents = ColliderEvents,
        BanterCone = Cone,
        BanterCylinder = Cylinder,
        BanterFermet = Fermet,
        BanterGeometry = Geometry,
        BanterGLTF = GLTF,
        BanterGrababble = Grababble,
        BanterGrabHandle = GrabHandle,
        BanterHeldEvents = HeldEvents,
        BanterHelicoid = Helicoid,
        BanterHorn = Horn,
        BanterInvertedMesh = InvertedMesh,
        BanterKitItem = KitItem,
        BanterKlein = Klein,
        BanterMaterial = Material,
        BanterMirror = Mirror,
        BanterMobius = Mobius,
        BanterMobius3d = Mobius3d,
        BanterMonoBehaviour = MonoBehaviour,
        BanterNatica = Natica,
        BanterPhysicMaterial = PhysicMaterial,
        BanterPhysicsMaterial = PhysicsMaterial,
        BanterPillow = Pillow,
        BanterPlane = Plane,
        BanterPortal = Portal,
        BanterQuestHome = QuestHome,
        BanterRigidbody = Rigidbody,
        BanterRing = Ring,
        BanterScherk = Scherk,
        BanterSkinnedMeshRenderer = SkinnedMeshRenderer,
        BanterSnail = Snail,
        BanterSphere = Sphere,
        BanterSpiral = Spiral,
        BanterSpring = Spring,
        BanterStreetView = StreetView,
        BanterSyncedObject = SyncedObject,
        BanterText = Text,
        BanterTorus = Torus,
        BanterTorusKnot = TorusKnot,
        BanterUIPanel = UIPanel,
        BanterVideoPlayer = VideoPlayer,
        BanterWorldObject = WorldObject,
    }
}
