namespace Banter.SDK
{
    public enum ComponentType
    {
        BanterAssetBundle,
        BanterAttachedObject,
        BanterAudioSource,
        BanterBillboard,
        BoxCollider,
        BanterBrowser,
        CapsuleCollider,
        BanterColliderEvents,
        ConfigurableJoint,
        BanterGeometry,
        BanterGLTF,
        BanterGrabHandle,
        BanterHeldEvents,
        BanterInvertedMesh,
        BanterKitItem,
        BanterMaterial,
        MeshCollider,
        BanterMirror,
        BanterPhysicMaterial,
        BanterPortal,
        BanterRigidbody,
        SphereCollider,
        BanterStreetView,
        BanterSyncedObject,
        BanterText,
        Transform,
        BanterVideoPlayer,
        BanterWorldObject,
    }
}
