name: CI
on:
  workflow_dispatch:
    
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main

    - name: Calculate Tag
      id: tag
      run: |
        TAG=$(jq -r '.version' package.json)
        echo "TAG=$TAG" >> $GITHUB_ENV
        if git rev-parse $TAG >/dev/null 2>&1; then
            echo ""::error::Tag already exists: $TAG"
        else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
        fi

    - name: Publish on UPM branch
      run: |
        if [[ -d "Samples" ]]; then
          git mv Samples Samples~
          rm -f Samples.meta
        fi

        mkdir ../upm
        cp -r . ../upm
        rm -rf ../upm/.git # don't want to replace git history!

        # WORKING UP TO HERE!!

        git reset --hard HEAD
        git checkout upm
        cp -r ../upm/* .

        rm -rf ../upm

        git add .
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git commit -m "$TAG" --no-verify
        git push -u origin upm

    - name: Create Release
      if: env.TAG_EXISTS == 'false'
      run: |
        git tag ${{ env.TAG }} main
        git push origin --tags
