name: Publish Package
on:
  workflow_dispatch:
    
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main

    - name: Calculate Tag
      id: tag
      run: |
        TAG=$(jq -r '.version' package.json)
        echo "TAG=$TAG" >> $GITHUB_ENV
        if git rev-parse $TAG >/dev/null 2>&1; then
            echo "::error::Tag already exists: $TAG"
            exit 1
        else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
        fi

    - name: Publish on UPM branch
      run: |
        if [[ -d "Samples" ]]; then
          git mv Samples Samples~
          rm -f Samples.meta
        fi

        mkdir ../upm
        cp -r . ../upm
        rm -rf ../upm/.git # don't want to replace git history!

        git reset --hard HEAD
        git checkout upm

        # Remove all files except .git
        git rm -rf .
        
        # Copy back the files
        cp -r ../upm/. .
        rm -rf ../upm

        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git add .
        git commit -am "$TAG" --no-verify
        git push -u origin upm

    - name: Create Release
      if: env.TAG_EXISTS == 'false'
      run: |
        git tag ${{ env.TAG }} upm
        git push origin --tags
