name: Publish Package
on:
  workflow_dispatch:
    
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main

    - name: Calculate Tag
      id: tag
      run: |
        TAG=$(jq -r '.version' package.json)
        echo "TAG=$TAG" >> $GITHUB_ENV
        if git rev-parse $TAG >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
            echo "::error::Tag already exists: $TAG"
            exit 1
        else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
        fi

    - name: Create Release
      if: env.TAG_EXISTS == 'false'
      run: |
        git tag ${{ env.TAG }} main
        git push origin --tags
